pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'product-service'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        REGISTRY = 'localhost:5000' // Local registry or Docker Hub username
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('backend/product-service') {
                    sh './mvnw clean package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend/product-service') {
                    sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                    sh "docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }

        // stage('Docker Push') {
        //     steps {
        //         sh "docker push ${REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}"
        //     }
        // }
    }
}
